apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    app: ft_services
spec:
  ports:
  - port: 8086
    targetPort: 8086
  selector:
    app: ft_services
    tier: influxdb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pv-claim
  labels:
    app: ft_services
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  labels:
    app: ft_services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ft_services
      tier: influxdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ft_services
        tier: influxdb
    spec:
      containers:
      - image: custom_influxdb
        imagePullPolicy: Never
        name: influxdb
        ports:
        - containerPort: 8086
          name: influxdb
        volumeMounts:
          - name: influx-persistent-storage
            mountPath: /var/lib/influxdb
      volumes:
      - name: influx-persistent-storage
        persistentVolumeClaim: