apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ft-service-ingress
  labels:
    app: ingress-controller
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
        - path: /
          backend:
            serviceName: nginx-svc
            servicePort: 80
        - path: /phpmyadmin
          backend:
            serviceName: phpmyadmin-svc
            servicePort: 5000
        - path: /wordpress
          backend:
            serviceName: wordpress
            servicePort: 5050